version: "3.8"

services:
  phi-annotator:
    image: docker.synapse.org/syn22277123/phi-annotator-neuroner:1.1.0
    build:
      context: server
    container_name: phi-annotator
    networks:
      - nlpsandbox-internal
    deploy:
      resources:
        limits:
          memory: 7G

  nginx:
    image: nginx:1.19.6-alpine
    container_name: phi-annotator-nginx
    restart: always
    environment:
      - TOOL_HOST=phi-annotator
      - TOOL_PORT=8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/templates:/etc/nginx/templates:ro
    networks:
      - nlpsandbox
      - nlpsandbox-internal
    ports:
      - "80:80"
    depends_on:
      - phi-annotator

networks:
  nlpsandbox:
  nlpsandbox-internal:
    internal: true
